### Numpy 리뷰 
- numpy 와 pytorch 는 호환성이 높고, 직관적

In [3]:
import numpy as np
import torch

In [8]:
# 1D Array 
t = np.array([0.,1.,2.,3.,4.,5.,6.]) # 1d vector 
print(t)



[0. 1. 2. 3. 4. 5. 6.]


In [9]:
print('Rank of t: ', t.ndim) # 몇 개의 차원으로 이루어진 백터(텐서)니? 
print('Shape of t: ', t.shape) # shape는 어떻니 ? A : 하나의 차원에 대해서 7개의 elemenet가 들어있어 

Rank of t:  1
Shape of t:  (7,)


In [10]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # element 
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) # slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [12]:
# 2D array
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [13]:
print('Rank of t: ', t.ndim) # 몇 차원이니 ? 
print('Shape of t: ', t.shape) # shape 는 어떻니 ? A : 4 X 3 

Rank of t:  2
Shape of t:  (4, 3)


### Pytorch


In [15]:
# 1D array 
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [18]:
print(t.dim()) # rank 
print(t.shape) # shape 
print(t.size()) # shape
print(t[0], t[1], t[-1]) # Element 
print(t[2:5], t[4:-1]) # Slicing
print(t[:2], t[3:]) # Slicing 

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [19]:
# 2D array 
t = torch.FloatTensor([[1., 2., 3.], 
                      [4., 5., 6.], 
                      [7., 8., 9.], 
                      [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [21]:
print(t.dim()) # rank  # 2개의 차원에 
print(t.size()) # shape  # 4개, 3개의 element가 있다 
print(t[:, 1])  # 2번째 element를 가져와 
print(t[:, 1].size()) # 4개의 element를 가진 벡터야. 
print(t[:, :-1]) 

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [26]:
# Same Shape 
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [28]:
# Vector + scalar 
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [29]:
# 2 x 1 Vectory + 1 x 2 Vector 
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Multiplication vs Matrix Multiplication

In [37]:
print() 
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 2
print(m1.matmul(m2))
print(m1.mul(m2))
print(m1 * m2)


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean 

In [38]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [40]:
# Can't use mean() on integers 
t = torch.LongTensor([1, 2])
try: 
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [41]:
t = torch.FloatTensor([[1, 2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [42]:
# https://pytorch.org/docs/stable/torch.html#torch.mean

print(t.mean())
print(t.mean(dim=0)) # dim (python:int or tuple of python:ints) – the dimension or dimensions to reduce.
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum 

In [48]:
t = torch.FloatTensor([[1, 2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [49]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argumax


In [53]:
t = torch.FloatTensor([[1,2], [3,50]])
print(t)


tensor([[ 1.,  2.],
        [ 3., 50.]])


In [54]:
print(t.max()) # 가장 큰 값을 찾아준다 

tensor(50.)


In [62]:
print(t.max(dim=0)) # 가장 큰 값과 그 인덱스를 찾아준다 
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

(tensor([ 3., 50.]), tensor([1, 1]))
Max:  tensor([ 3., 50.])
Argmax:  tensor([1, 1])


In [64]:
print(t.max(dim=1))
print(t.max(dim=-1))

(tensor([ 2., 50.]), tensor([1, 1]))
(tensor([ 2., 50.]), tensor([1, 1]))
